name: Deploy Only

on: workflow_dispatch


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: site
          path: artifacts

      - name: Print directory structure
        run: |
          echo "Contents of artifacts directory:"
          tree
          ls -al artifacts

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: artifacts
          publish_branch: gh-pages

      - name: Remove HTML files
        run: |
          find artifacts -name '*.html' -exec rm {} \;
          
      - name: Deploy remaining artifacts
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: artifacts
          publish_branch: artifacts