name: Go Live

on: workflow_dispatch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Install Git
        run: sudo apt-get install git

      - name: Set up Git
        run: |
          git config --global user.name "Jonathan Graves"
          git config --global user.email "jonathan.graves@ubc.ca"

      - name: Add GitLab as a remote
        run: git remote add gitlab https://repo.code.ubc.ca/arts-isit/tlef/comet-website-deployment/

      - name: Push to GitLab gh-pages branch
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}  # Store your GitLab token in GitHub Secrets
        run: |
          git push --force gitlab gh-pages:gh-pages
